"""
machine_learning.py
-------------------
Unsupervised Machine Learning pipeline for anomaly detection using
scikit-learn's Isolation Forest algorithm.

Replaces the hardcoded heuristic standard deviations with a model that
dynamically learns the "normal" multivariate behavior cluster across a rolling 1-year window.
"""

import pandas as pd
from sklearn.ensemble import IsolationForest
from sklearn.preprocessing import StandardScaler

def train_and_predict_iforest(stock_df: pd.DataFrame, nifty_df: pd.DataFrame, demo_mode: bool = False) -> float:
    """
    Fits an Isolation Forest model to historical features and returns the anomaly score 
    for the most recent trading day, scaled 0 to 100.
    
    If data is insufficient (< 10 days), returns 0.0 to prevent overfitting safely.
    """
    if len(stock_df) < 10 or nifty_df is None or len(nifty_df) < 10:
        return 0.0

    # Clean the DataFrames to match indexes safely
    n_recent = min(len(stock_df), len(nifty_df))
    s_feat = stock_df.tail(n_recent).copy()
    n_feat = nifty_df.tail(n_recent).copy()

    # Align indexes explicitly (inner join to avoid NaNs on disjoint days)
    df = s_feat.join(n_feat[["Close"]], how="inner", rsuffix="_NIFTY")
    
    if len(df) < 10:
        return 0.0

    # -------------------------------------------------------------
    # 1. FEATURE ENGINEERING
    # Extract structural behavioral features for clustering
    # -------------------------------------------------------------
    
    # Feature 1: Stock Daily Return %
    df["Return"] = df["Close"].pct_change()
    
    # Feature 2: Index Daily Return %
    df["Index_Return"] = df["Close_NIFTY"].pct_change()
    
    # Feature 3: Relative Strength (Stock - Index Return)
    df["Relative_Return"] = df["Return"] - df["Index_Return"]
    
    # Feature 4: Relative Volume Spike (Current Vol / 20-Day SMA Vol)
    # Using expanding if 20 rolling is unavailable
    df["Vol_20SMA"] = df["Volume"].rolling(window=20, min_periods=5).mean()
    df["Volume_Spike_Ratio"] = df["Volume"] / df["Vol_20SMA"]
    
    # Feature 5: Rolling Volatility Shift (5-Day StdDev of Returns)
    df["Volatility_5D"] = df["Return"].rolling(window=5, min_periods=2).std()

    # Feature 6: Relative Strength Index (14-Day Momentum)
    # Using an SMA approach for performance simplicity over EMA
    delta = df["Close"].diff()
    gain = delta.where(delta > 0, 0).rolling(window=14, min_periods=14).mean()
    loss = (-delta.where(delta < 0, 0)).rolling(window=14, min_periods=14).mean()
    rs = gain / loss
    df["RSI_14"] = 100 - (100 / (1 + rs))
    
    # Fill edge case divided-by-zero NaNs or lack of data with neutral 50 values
    df["RSI_14"] = df["RSI_14"].fillna(50)

    # Drop NaNs generated by rolling/pct_change operations
    df_clean = df.dropna()
    
    if len(df_clean) < 5:
        return 0.0

    # Features to push into the model
    features = ["Return", "Relative_Return", "Volume_Spike_Ratio", "Volatility_5D", "RSI_14"]
    X = df_clean[features].values

    # -------------------------------------------------------------
    # 2. MACHINE LEARNING PIPELINE
    # -------------------------------------------------------------
    
    # Standardize features (Mean=0, StdDev=1) so large volumes don't dominate % returns
    scaler = StandardScaler()
    X_scaled = scaler.fit_transform(X)

    if demo_mode:
        # Force massive mathematical anomalies into the most recent day
        # Features: [Return, Relative_Return, Volume_Spike_Ratio, Volatility_5D, RSI_14]
        X_scaled[-1] = [15.0, 15.0, 60.0, 30.0, 99.0]

    # Instantiate Isolation Forest Model
    # Contamination=0.05 implies we expect ~5% of trading days historically are "anomalous"
    model = IsolationForest(contamination=0.05, random_state=42, n_estimators=100)
    
    # Fit the cluster boundaries based on the 1-year array
    model.fit(X_scaled)
    
    # Get standard decision_function anomaly scores (Inliers > 0, Outliers < 0)
    raw_scores = model.decision_function(X_scaled)
    
    # Evaluate the *most recent* trading day (the last row)
    target_score = raw_scores[-1]
    target_pred = model.predict(X_scaled)[-1] # -1 if anomaly, 1 if normal

    # -------------------------------------------------------------
    # 3. SCORE NORMALIZATION
    # Translate arbitrary SKLearn margins to a 0-100 Gauge Score
    # -------------------------------------------------------------
    
    # SKLearn decision scores generally range from roughly -0.5 (extreme anomaly) to 0.2 (very normal)
    # We want to invert and scale this so -0.5 -> 100 Manipulation Risk
    # and >0 -> 0 Manipulation Risk
    
    if target_score >= 0:
        manipulation_score = 0.0 # Completely normal
    else:
        # Score is negative. Min score is usually theoretically -1.0 but practically rarely below -0.4
        # We cap it at -0.3 as the maximum boundary for mapping
        clamped_score = max(target_score, -0.3) 
        
        # Map (-0.3 to 0.0) -> (100 to 0)
        # e.g. -0.15 = 50, -0.3 = 100
        manipulation_score = (abs(clamped_score) / 0.3) * 100
    
    return round(manipulation_score, 2)
