"""
machine_learning.py
-------------------
Unsupervised Machine Learning pipeline for anomaly detection using
scikit-learn's Isolation Forest algorithm.

Replaces the hardcoded heuristic standard deviations with a model that
dynamically learns the "normal" multivariate behavior cluster across a rolling 1-year window.

Public API
----------
train_and_predict_iforest(stock_df, nifty_df, demo_mode)
    -> float  anomaly score (0-100) for the MOST RECENT trading day.

score_history_iforest(stock_df, nifty_df, n_days)
    -> pd.Series  anomaly score (0-100) for EACH of the last `n_days` sessions.

build_anomaly_matrix(constituent_dfs, nifty_df, n_days)
    -> pd.DataFrame  rows = tickers, cols = dates, values = anomaly score (0-100).
       This is the data source for the dashboard anomaly heatmap.
"""

import numpy as np
import pandas as pd
from sklearn.ensemble import IsolationForest
from sklearn.preprocessing import StandardScaler

# The 5 engineered features fed to the Isolation Forest.
FEATURES = ["Return", "Relative_Return", "Volume_Spike_Ratio", "Volatility_5D", "RSI_14"]

# Isolation Forest hyper-parameters (kept in one place so every entry point
# - single-day score, history, and heatmap - uses an identical model spec).
CONTAMINATION = 0.05    # assumed ~5% of historical sessions are anomalous
N_ESTIMATORS  = 100
RANDOM_STATE  = 42

# decision_function margin at which we saturate the 0-100 display scale.
SCORE_FLOOR = -0.3

# Minimum clean rows required before we trust the model at all.
MIN_ROWS = 10
MIN_CLEAN_ROWS = 5


# ---------------------------------------------------------------------------
# FEATURE ENGINEERING
# ---------------------------------------------------------------------------

def _build_feature_frame(stock_df: pd.DataFrame, nifty_df: pd.DataFrame):
    """
    Build the 5-feature matrix used by the Isolation Forest.

    Returns a DataFrame containing at least the FEATURES columns (indexed by
    date), or None when there is not enough clean data to model safely.
    """
    if stock_df is None or nifty_df is None:
        return None
    if len(stock_df) < MIN_ROWS or len(nifty_df) < MIN_ROWS:
        return None

    # Clean the DataFrames to match indexes safely
    n_recent = min(len(stock_df), len(nifty_df))
    s_feat = stock_df.tail(n_recent).copy()
    n_feat = nifty_df.tail(n_recent).copy()

    # Align indexes explicitly (inner join to avoid NaNs on disjoint days)
    df = s_feat.join(n_feat[["Close"]], how="inner", rsuffix="_NIFTY")

    if len(df) < MIN_ROWS:
        return None

    # Feature 1: Stock Daily Return %
    df["Return"] = df["Close"].pct_change()

    # Feature 2: Index Daily Return % (context for Relative_Return below)
    df["Index_Return"] = df["Close_NIFTY"].pct_change()

    # Feature 3: Relative Strength (Stock - Index Return)
    df["Relative_Return"] = df["Return"] - df["Index_Return"]

    # Feature 4: Relative Volume Spike (Current Vol / 20-Day SMA Vol)
    df["Vol_20SMA"] = df["Volume"].rolling(window=20, min_periods=5).mean()
    df["Volume_Spike_Ratio"] = df["Volume"] / df["Vol_20SMA"]

    # Feature 5: Rolling Volatility Shift (5-Day StdDev of Returns)
    df["Volatility_5D"] = df["Return"].rolling(window=5, min_periods=2).std()

    # Feature 6: Relative Strength Index (14-Day Momentum)
    # Using an SMA approach for performance simplicity over EMA
    delta = df["Close"].diff()
    gain = delta.where(delta > 0, 0).rolling(window=14, min_periods=14).mean()
    loss = (-delta.where(delta < 0, 0)).rolling(window=14, min_periods=14).mean()
    rs = gain / loss
    df["RSI_14"] = 100 - (100 / (1 + rs))

    # Fill edge case divided-by-zero NaNs or lack of data with neutral 50 values
    df["RSI_14"] = df["RSI_14"].fillna(50)

    # Guard against inf produced by a zero-volume baseline before dropna
    df = df.replace([np.inf, -np.inf], np.nan)

    # Drop NaNs generated by rolling/pct_change operations
    df_clean = df.dropna(subset=FEATURES)

    if len(df_clean) < MIN_CLEAN_ROWS:
        return None

    return df_clean


# ---------------------------------------------------------------------------
# MODEL + SCORE NORMALIZATION
# ---------------------------------------------------------------------------

def _normalize_scores(raw_scores: np.ndarray) -> np.ndarray:
    """
    Translate arbitrary sklearn decision_function margins to a 0-100 gauge score.

    decision_function returns > 0 for inliers and < 0 for outliers. Margins in
    practice rarely fall below -0.3, so we clamp there and map:
        >=  0.0  ->   0   (completely normal)
           -0.15 ->  50
        <= -0.3  -> 100   (extreme anomaly)

    NOTE: this is a display normalization, not a calibrated probability.
    """
    clamped = np.clip(raw_scores, SCORE_FLOOR, 0.0)
    return np.round(np.abs(clamped) / abs(SCORE_FLOOR) * 100, 2)


def _fit_and_score(X: np.ndarray, demo_mode: bool = False) -> np.ndarray:
    """
    Standardize, fit an Isolation Forest, and return a 0-100 anomaly score
    for every row of X.

    The model is fit on the same window it scores: this is the standard
    transductive setup for unsupervised outlier detection - the forest learns
    the distribution of the window and reports how isolated each session is
    within it. There is no label to hold out.
    """
    # Standardize features (Mean=0, StdDev=1) so large volumes don't dominate % returns
    scaler = StandardScaler()
    X_scaled = scaler.fit_transform(X)

    if demo_mode:
        # Force massive mathematical anomalies into the most recent day
        # Features: [Return, Relative_Return, Volume_Spike_Ratio, Volatility_5D, RSI_14]
        X_scaled[-1] = [15.0, 15.0, 60.0, 30.0, 99.0]

    model = IsolationForest(
        contamination=CONTAMINATION,
        random_state=RANDOM_STATE,
        n_estimators=N_ESTIMATORS,
    )
    model.fit(X_scaled)

    raw_scores = model.decision_function(X_scaled)
    return _normalize_scores(raw_scores)


# ---------------------------------------------------------------------------
# PUBLIC: SINGLE-DAY SCORE
# ---------------------------------------------------------------------------

def train_and_predict_iforest(
    stock_df: pd.DataFrame,
    nifty_df: pd.DataFrame,
    demo_mode: bool = False,
) -> float:
    """
    Fits an Isolation Forest model to historical features and returns the anomaly score
    for the most recent trading day, scaled 0 to 100.

    If data is insufficient (< 10 days), returns 0.0 to prevent overfitting safely.
    """
    df_clean = _build_feature_frame(stock_df, nifty_df)
    if df_clean is None:
        return 0.0

    scores = _fit_and_score(df_clean[FEATURES].values, demo_mode=demo_mode)
    return float(scores[-1])


# ---------------------------------------------------------------------------
# PUBLIC: SCORE HISTORY  (per-day, one model per stock)
# ---------------------------------------------------------------------------

def score_history_iforest(
    stock_df: pd.DataFrame,
    nifty_df: pd.DataFrame,
    n_days: int = 30,
) -> pd.Series:
    """
    Return the Isolation Forest anomaly score (0-100) for each of the last
    `n_days` trading sessions.

    One model is fit per stock over the full available window, then every
    session in that window is scored against it - so the scores along a single
    heatmap row are directly comparable.

    Returns an empty Series when there is not enough data.
    """
    df_clean = _build_feature_frame(stock_df, nifty_df)
    if df_clean is None:
        return pd.Series(dtype=float)

    scores = _fit_and_score(df_clean[FEATURES].values)
    series = pd.Series(scores, index=df_clean.index, name="anomaly_score")
    return series.tail(n_days)


# ---------------------------------------------------------------------------
# PUBLIC: ANOMALY MATRIX  (stocks x dates -> heatmap)
# ---------------------------------------------------------------------------

def build_anomaly_matrix(
    constituent_dfs: dict,
    nifty_df: pd.DataFrame,
    n_days: int = 30,
) -> pd.DataFrame:
    """
    Score every stock in `constituent_dfs` across the last `n_days` sessions.

    Parameters
    ----------
    constituent_dfs : dict  {ticker: OHLCV DataFrame}
    nifty_df        : pd.DataFrame  index data, used for the Relative_Return feature
    n_days          : int   number of trailing sessions to report

    Returns
    -------
    pd.DataFrame
        rows    = tickers (sorted by peak anomaly score, most anomalous first)
        columns = dates ascending
        values  = anomaly score 0-100, NaN where a stock had insufficient data
    """
    rows = {}
    for ticker, df in constituent_dfs.items():
        if df is None or df.empty:
            continue
        series = score_history_iforest(df, nifty_df, n_days=n_days)
        if series.empty:
            continue
        rows[ticker] = series

    if not rows:
        return pd.DataFrame()

    matrix = pd.DataFrame(rows).T          # tickers as rows, dates as columns
    matrix = matrix.sort_index(axis=1)     # dates ascending

    # Normalize the column labels to plain dates for clean axis ticks
    matrix.columns = [
        c.strftime("%Y-%m-%d") if hasattr(c, "strftime") else str(c)
        for c in matrix.columns
    ]

    # Rank rows so the most anomalous stocks surface at the top of the heatmap
    order = matrix.max(axis=1).sort_values(ascending=False).index
    return matrix.loc[order]
